services:
  - type: web
    name: paycontrol-backend
    runtime: node
    rootDir: backend
    buildCommand: npm install
    startCommand: node server.js
    autoDeploy: true
    env:
      FRONTEND_URL: https://paycontrol-ivory.vercel.app
